// <auto-generated />
using System;
using AniRate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AniRate.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220428120321_NewArch")]
    partial class NewArch
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnimeCollectionAnimeTitle", b =>
                {
                    b.Property<Guid>("AnimeCollectionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimeTitlesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AnimeCollectionsId", "AnimeTitlesId");

                    b.HasIndex("AnimeTitlesId");

                    b.ToTable("AnimeCollectionAnimeTitle");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.AnimeCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ImageId");

                    b.ToTable("AnimeCollections");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.AnimeTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiredOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Episodes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReleasedOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Russian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("AnimeTitles");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.AnimeUserRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("AnimeUserRates");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.CollectionUserRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CollectionUserRates");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Russian")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Original")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("X48")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("X96")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("AnimeCollectionAnimeTitle", b =>
                {
                    b.HasOne("AniRate.Domain.Entities.AnimeCollection", null)
                        .WithMany()
                        .HasForeignKey("AnimeCollectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniRate.Domain.Entities.AnimeTitle", null)
                        .WithMany()
                        .HasForeignKey("AnimeTitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniRate.Domain.Entities.AnimeCollection", b =>
                {
                    b.HasOne("AniRate.Domain.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.AnimeUserRate", b =>
                {
                    b.HasOne("AniRate.Domain.Entities.AnimeTitle", "AnimeTitle")
                        .WithMany("UserRates")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimeTitle");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.CollectionUserRate", b =>
                {
                    b.HasOne("AniRate.Domain.Entities.AnimeCollection", "AnimeCollection")
                        .WithMany("UserRates")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimeCollection");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.Genre", b =>
                {
                    b.HasOne("AniRate.Domain.Entities.AnimeTitle", "AnimeTitle")
                        .WithMany("Genres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimeTitle");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.Image", b =>
                {
                    b.HasOne("AniRate.Domain.Entities.AnimeTitle", "AnimeTitle")
                        .WithOne("Image")
                        .HasForeignKey("AniRate.Domain.Entities.Image", "AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimeTitle");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.AnimeCollection", b =>
                {
                    b.Navigation("UserRates");
                });

            modelBuilder.Entity("AniRate.Domain.Entities.AnimeTitle", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("Image");

                    b.Navigation("UserRates");
                });
#pragma warning restore 612, 618
        }
    }
}
