version: "3.3"
services:
  backend:
    image: "aniratewebapi_backend"
    container_name: anirate_backend
    #build:
    #  context: ..
    #  dockerfile: ./AniRate.WebApi/Dockerfile
    depends_on: [ mssql ]
    ports:
      - "5000:80"




  mssql:
    #image: "mcr.microsoft.com/mssql/server"
    image: "vitaliytyu/anirate_db:1000"
    container_name: mssql
    hostname: mssql
    #environment:
    #  SA_PASSWORD: "Pass123!"
    #  ACCEPT_EULA: "Y"
    restart: unless-stopped    
    ports:
      - "11433:1433" 


  client:
    image: vitaliytyu/anirate_client:2.0
    container_name: anirate_client
    ports:
      - "5001:3000"

  proxy:
    image: nginx:mainline
    container_name: anirate_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
